### ISSUE TITLE
RandomCoords crashing the server

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#7] opened 2017-03-13 20:13 UTC
Crashlog: http://pastebin.com/PsYy6Jvv

**Comment by jolbol1** [comment] 2017-03-13 20:19
It would appear that It was checking for WorldGuard, Have you got this feature enabled?

**Comment by Sikatsu** [comment] 2017-03-13 20:22
I do indeed

Op ma 13 mrt. 2017 21:19 schreef jolbol1 <notifications@github.com>:

**Comment by jolbol1** [comment] 2017-03-13 20:24
Are you running the latest version of WorldGuard?

**Comment by Sikatsu** [comment] 2017-03-13 20:27
One of the latest devbuilds

Op ma 13 mrt. 2017 21:24 schreef jolbol1 <notifications@github.com>:

**Comment by jolbol1** [comment] 2017-03-13 20:30
It might be an easy fix Im currently looking into it but having some serious issues my side.

**Comment by Sikatsu** [comment] 2017-03-13 20:37
Alright, hope it can be fixed. Servers crashes are a huge problem. Issues
on your side? :o

Op ma 13 mrt. 2017 21:30 schreef jolbol1 <notifications@github.com>:

**Comment by jolbol1** [comment] 2017-03-13 20:38
Ok so an update, On my end the WorldGuard feature is working fine. The error points to the method to get the world Guard plugin. Has this been a regular occurrence or is this the first time, and if so did you do anything differently?

**Comment by Sikatsu** [comment] 2017-03-13 20:45
This was the first time the server crashed. But I'm only using the plugin
officially since a couple of hours. I wasn't online at the time of the
crash, however. Is the stacktrace complete enough?

Op ma 13 mrt. 2017 21:38 schreef jolbol1 <notifications@github.com>:

**Comment by jolbol1** [comment] 2017-03-13 20:46
The stack trace should be complete enough unless there were further errors above it from Worldguard itself maybe? 

How many players were on at this time / Whats the average?

**Comment by Sikatsu** [comment] 2017-03-13 21:08
Around 10 players, not that much. Most are sleeping by now. Over the day
the average would br 30-35.

Op ma 13 mrt. 2017 21:46 schreef jolbol1 <notifications@github.com>:

**Comment by jolbol1** [comment] 2017-03-13 21:13
This bug is confusing me. In my code, I see no errors, and I am unable to replicate this in any way. To describe the normal working process, When doing /RC, it checks for WorldGuard, and checks if the coordinates in a blocked region. This plugin is going wrong on your server at the point of checking for world guard which is odd because the code is correct. Do you have a larger stack trace?

**Comment by jolbol1** [comment] 2017-03-14 10:34
At this point, I see no errors in my code. As stated before this crash has been caused by trying to access WorldGuard and it seemingly not being there. I have added to the getPlugin code in my latest build to attempt to check for this. Please do let me know if it crashes again and if so please provide the full stack trace.

I'm very sorry about this,
Jolbol1.

**Comment by Sikatsu** [comment] 2017-03-14 12:06
Now while i'm back at my pc I notice you edited some comments, this didn't show up in the email however. Sorry for that.

Let me provide you more information.

Java version: 8, b121.
Worldguard version: (6.2.1-SNAPSHOT;1703-85693b9)
Larger stack trace: http://pastebin.com/w10jzXk8

**Comment by jolbol1** [comment] 2017-03-14 12:15
Thanks for the reply. The stack trace doesn't provide much more information about my plugin than before. All I can see is tat Bukkit's method for finding the WorldGuard plugin didn't work and caused this all. I have readded a null check in the upcoming version however it shouldn't have been needed, But may fix the issue. 

As a side note, BannerBoard is also in that stack trace, but that could just be due to mine crashing first causing its code to fail.

**Comment by Sikatsu** [comment] 2017-03-14 12:22
Someone was interacting with a bannerboard right before the crash occured, that might be why it's in the stacktrace.

Thanks, I will inform you if it still happens with the new version.

**Comment by jolbol1** [comment] 2017-03-14 12:39
https://dev.bukkit.org/projects/randomcoordinates/files/2393011

**Comment by Sikatsu** [comment] 2017-03-14 13:01
It notifies me about 0.0.9-RELEASE btw :)

**Comment by Sikatsu** [comment] 2017-03-14 13:07
I believe you edited my message haha!

**Comment by jolbol1** [comment] 2017-03-14 13:07
Oh whoops, Meant to reply lol!

**Comment by jolbol1** [comment] 2017-03-15 23:40
Closing this until further notice.

My best guess is that the server crashed first, causing WorldGuard to gain down while my plugin attempted to check for it.

Please do let me know if this happens again, As I will look even further into it.

**Closed** 2017-03-15 23:41 UTC
Labels: Possibly Fixed
